name: Build and Publish Executable

on:
  push:
    branches:
      - main
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        
    - name: Build executable
      run: pyinstaller --onefile export_report_tmas.py
      
    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: export_report_tmas
        path: dist/export_report_tmas

  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    
    steps:
    - name: Download Executable
      uses: actions/download-artifact@v4
      with:
        name: export_report_tmas
        
    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: export_report_tmas/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
