name: Build Executable

on:
  push:
    tags:
      - '*'

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' 

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build the .exe with PyInstaller
      run: |
        pyinstaller --onefile export_report_tmas.py  # Reemplaza con el nombre de tu script

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/export_report_tmas.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
